# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
	vb.customize ["modifyvm", :id, "--memory", 1024 * 4]
  end

  config.vm.provision "file", source: "default", destination: "~/default"
  config.vm.provision "file", source: "user-mapping.xml", destination: "~/user-mapping.xml"
  config.vm.provision "file", source: "cert.txt", destination: "~/cert.txt"
  config.vm.provision "file", source: "userpass.txt", destination: "~/userpass.txt"

  config.vm.provision "shell", inline: <<-SHELL
  	groupadd ssl-cert && groupadd docker && groupadd wireshark && groupadd libvirt
	useradd xrdp
	useradd -m -G wireshark,libvirt,docker student
	passwd student < /home/vagrant/userpass.txt
	usermod -aG ssl-cert xrdp
  	apt-get install ca-certificates curl gnupg
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
	echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
	add-apt-repository ppa:gns3/ppa
	apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gns3-gui gns3-server docker-ce lxqt-core lxqt-qtplugin gns3-gui gns3-server firefox nginx xrdp 
	cp /home/vagrant/default /etc/nginx/sites-enabled/default
	docker volume create guac-home
    docker run -v guac-home:/data --name helper busybox true
    docker cp /home/vagrant/user-mapping.xml helper:/data
    docker rm helper
  SHELL

  config.vm.provision "docker" do |d|
	d.pull_images "guacamole/guacamole"
	d.pull_images "guacamole/guacd"
	d.run "guacamole/guacd",
	  args: "--network host --name guacd"
	d.run "guacamole/guacamole",
	  args: "-v guac-home:/guac-home --env GUACD_HOSTNAME=localhost --env GUACAMOLE_HOME=/guac-home --name guacamole --network host"
  end

  config.vm.provision "shell", inline: <<-SHELL
  	sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/conf.d/selfsigned.key -out /etc/nginx/conf.d/selfsigned.crt < /home/vagrant/cert.txt
	sudo systemctl restart nginx
  	yes | ufw enable
    ufw allow 22,80,443/tcp
    ufw allow from 127.0.0.1 to 127.0.0.1 port 3389,4882,8080 proto tcp
	mkdir -p /home/student/.config/autostart
    chown -R student:student /home/student/.config
    cp /usr/share/applications/gns3.desktop /home/student/.config/autostart
  SHELL

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 4433


  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
end
